In [104]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [92]:
df=pd.read_csv('Hospital.csv')
df

,patient_id,age,age_group,gender,state,city,region,urban_rural,disease_name,disease_category,...,insurance_status,treatment_type,hospital_type,days_hospitalized,treatment_cost_inr,outcome,death_flag,cause_of_death,recovery_days,follow_up_required
0,IND-00000001,70,70-79,Female,Bihar,Patna,East,Semi-Urban,Diarrhea,Waterborne,...,Employer,Medication,Government,21,102.0,Recovering,0,NaN,42.0,Yes
1,IND-00000002,27,20-29,Other,Gujarat,Surat,West,Urban,Chikungunya,Vector-Borne,...,Uninsured,Medication,Government,0,1151.0,Recovered,0,NaN,18.0,Yes
2,IND-00000003,66,60-69,Other,Jharkhand,Bokaro,East,Rural,Hypertension,Non-Communicable,...,Private,Medication,Government,2,89.0,Chronic Management,0,NaN,NaN,Yes
3,IND-00000004,27,20-29,Female,Karnataka,Hubli,South,Rural,Tuberculosis,Infectious,...,Private,Surgery,Government,9,1269.0,Recovering,0,NaN,69.0,Yes
4,IND-00000005,40,40-49,Male,Karnataka,Belagavi,South,Rural,Chronic Kidney Disease,Non-Communicable,...,Ayushman Bharat,Palliative,Private,31,670576.0,Deceased,1,Complications from Chronic Kidney Disease,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,IND-00019996,73,70-79,Female,Uttar Pradesh,Agra,North,Semi-Urban,COPD,Respiratory,...,Private,Medication,Private,6,44863.0,Chronic Management,0,NaN,NaN,Yes
19996,IND-00019997,76,70-79,Female,Uttar Pradesh,Varanasi,North,Urban,Diarrhea,Waterborne,...,State Scheme,Medication,Private,1,1590.0,Recovered,0,NaN,14.0,Yes
19997,IND-00019998,21,20-29,Male,Uttar Pradesh,Meerut,North,Rural,Thalassemia,Genetic,...,Ayushman Bharat,Medication,Primary Health Center,8,11361.0,Chronic Management,0,NaN,NaN,Yes
19998,IND-00019999,48,40-49,Female,Uttar Pradesh,Varanasi,North,Rural,Diabetes (Type 2),Non-Communicable,...,Private,Home Remedies,Private,0,3307.0,Chronic Management,0,NaN,NaN,Yes
19999,IND-00020000,2,0-9,Male,West Bengal,Kolkata,East,Rural,Thalassemia,Genetic,...,Ayushman Bharat,Medication,Government,6,6667.0,Chronic Management,0,NaN,NaN,Yes

In [94]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 32 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20000 non-null  object
 1   age                 20000 non-null  int64
 2   age_group           20000 non-null  object
 3   gender              20000 non-null  object
 4   state               20000 non-null  object
 5   city                20000 non-null  object
 6   region              20000 non-null  object
 7   urban_rural         20000 non-null  object
 8   disease_name        20000 non-null  object
 9   disease_category    20000 non-null  object
 10  severity            20000 non-null  object
 11  diagnosis_date      20000 non-null  object
 12  year                20000 non-null  int64
 13  month               20000 non-null  object
 14  season              20000 non-null  object
 15  symptoms            20000 non-null  object
 16  comorbidity         13401 non-null  object
 17  smoking_status      20000 non-null  object
 18  alcohol_use         13373 non-null  object
 19  bmi                 20000 non-null  float64
 20  blood_group         20000 non-null  object
 21  income_level        20000 non-null  object
 22  insurance_status    20000 non-null  object
 23  treatment_type      20000 non-null  object
 24  hospital_type       20000 non-null  object
 25  days_hospitalized   20000 non-null  int64
 26  treatment_cost_inr  20000 non-null  float64
 27  outcome             20000 non-null  object
 28  death_flag          20000 non-null  int64
 29  cause_of_death      1822 non-null   object
 30  recovery_days       13693 non-null  float64
 31  follow_up_required  20000 non-null  object
dtypes: float64(3), int64(4), object(25)
memory usage: 4.9+ MB

In [96]:
df.drop(columns = ['follow_up_required','recovery_days','cause_of_death','death_flag','outcome','income_level','bmi','comorbidity','symptoms','severity','region','age_group','alcohol_use'],axis = 1 , inplace = True)

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   patient_id          20000 non-null  object
 1   age                 20000 non-null  int64
 2   gender              20000 non-null  object
 3   state               20000 non-null  object
 4   city                20000 non-null  object
 5   urban_rural         20000 non-null  object
 6   disease_name        20000 non-null  object
 7   disease_category    20000 non-null  object
 8   diagnosis_date      20000 non-null  object
 9   year                20000 non-null  int64
 10  month               20000 non-null  object
 11  season              20000 non-null  object
 12  smoking_status      20000 non-null  object
 13  blood_group         20000 non-null  object
 14  insurance_status    20000 non-null  object
 15  treatment_type      20000 non-null  object
 16  hospital_type       20000 non-null  object
 17  days_hospitalized   20000 non-null  int64
 18  treatment_cost_inr  20000 non-null  float64
dtypes: float64(1), int64(3), object(15)
memory usage: 2.9+ MB

In [100]:
df.isnull().sum()

patient_id            0
age                   0
gender                0
state                 0
city                  0
urban_rural           0
disease_name          0
disease_category      0
diagnosis_date        0
year                  0
month                 0
season                0
smoking_status        0
blood_group           0
insurance_status      0
treatment_type        0
hospital_type         0
days_hospitalized     0
treatment_cost_inr    0
dtype: int64

In [102]:
df.duplicated().sum()

0

In [148]:
# changing dataype 
df['Diagnosis_Date'] = pd.to_datetime(df['Diagnosis_Date'])

In [114]:
# creating Age_Group 
df['age_group'] = np.where(df['age'] <= 12 ,'Child',np.where(df['age'] <= 19 , 'Teen',np.where(df['age'] <= 59 ,'Adult','Senior')))

In [118]:
df[['age','age_group']]

       age age_group
0       70    Senior
1       27     Adult
2       66    Senior
3       27     Adult
4       40     Adult
...    ...       ...
19995   73    Senior
19996   76    Senior
19997   21     Adult
19998   48     Adult
19999    2     Child

[20000 rows x 2 columns]

In [128]:
df.columns = df.columns.str.strip().str.title()

In [130]:
#Fixing Text column
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip().str.title()

In [132]:
df

,Patient_Id,Age,Gender,State,City,Urban_Rural,Disease_Name,Disease_Category,Diagnosis_Date,Year,Month,Season,Smoking_Status,Blood_Group,Insurance_Status,Treatment_Type,Hospital_Type,Days_Hospitalized,Treatment_Cost_Inr,Age_Group
0,Ind-00000001,70,Female,Bihar,Patna,Semi-Urban,Diarrhea,Waterborne,2018-01-01,2018,January,Winter,Never,A+,Employer,Medication,Government,21,102.0,Senior
1,Ind-00000002,27,Other,Gujarat,Surat,Urban,Chikungunya,Vector-Borne,2018-01-01,2018,January,Winter,Never,O+,Uninsured,Medication,Government,0,1151.0,Adult
2,Ind-00000003,66,Other,Jharkhand,Bokaro,Rural,Hypertension,Non-Communicable,2018-01-01,2018,January,Winter,Never,B+,Private,Medication,Government,2,89.0,Senior
3,Ind-00000004,27,Female,Karnataka,Hubli,Rural,Tuberculosis,Infectious,2018-01-01,2018,January,Winter,Never,O-,Private,Surgery,Government,9,1269.0,Adult
4,Ind-00000005,40,Male,Karnataka,Belagavi,Rural,Chronic Kidney Disease,Non-Communicable,2018-01-01,2018,January,Winter,Former,A+,Ayushman Bharat,Palliative,Private,31,670576.0,Adult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,Ind-00019996,73,Female,Uttar Pradesh,Agra,Semi-Urban,Copd,Respiratory,2025-12-28,2025,December,Winter,Never,B+,Private,Medication,Private,6,44863.0,Senior
19996,Ind-00019997,76,Female,Uttar Pradesh,Varanasi,Urban,Diarrhea,Waterborne,2025-12-28,2025,December,Winter,Current,Ab+,State Scheme,Medication,Private,1,1590.0,Senior
19997,Ind-00019998,21,Male,Uttar Pradesh,Meerut,Rural,Thalassemia,Genetic,2025-12-28,2025,December,Winter,Never,O+,Ayushman Bharat,Medication,Primary Health Center,8,11361.0,Adult
19998,Ind-00019999,48,Female,Uttar Pradesh,Varanasi,Rural,Diabetes (Type 2),Non-Communicable,2025-12-28,2025,December,Winter,Never,B+,Private,Home Remedies,Private,0,3307.0,Adult
19999,Ind-00020000,2,Male,West Bengal,Kolkata,Rural,Thalassemia,Genetic,2025-12-28,2025,December,Winter,Current,A+,Ayushman Bharat,Medication,Government,6,6667.0,Child

In [138]:
#Validate Numeric Columns
df = df[df['Age'] > 0]
df = df[df['Treatment_Cost_Inr'] > 0]

In [158]:
#Final look Datatypes and Data 
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19799 entries, 0 to 19999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Patient_Id          19799 non-null  object
 1   Age                 19799 non-null  int64
 2   Gender              19799 non-null  object
 3   State               19799 non-null  object
 4   City                19799 non-null  object
 5   Urban_Rural         19799 non-null  object
 6   Disease_Name        19799 non-null  object
 7   Disease_Category    19799 non-null  object
 8   Diagnosis_Date      19799 non-null  datetime64[ns]
 9   Year                19799 non-null  int64
 10  Month               19799 non-null  object
 11  Season              19799 non-null  object
 12  Smoking_Status      19799 non-null  object
 13  Blood_Group         19799 non-null  object
 14  Insurance_Status    19799 non-null  object
 15  Treatment_Type      19799 non-null  object
 16  Hospital_Type       19799 non-null  object
 17  Days_Hospitalized   19799 non-null  int64
 18  Treatment_Cost_Inr  19799 non-null  float64
 19  Age_Group           19799 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(3), object(15)
memory usage: 3.2+ MB

In [154]:
df.head()

,Patient_Id,Age,Gender,State,City,Urban_Rural,Disease_Name,Disease_Category,Diagnosis_Date,Year,Month,Season,Smoking_Status,Blood_Group,Insurance_Status,Treatment_Type,Hospital_Type,Days_Hospitalized,Treatment_Cost_Inr,Age_Group
0,Ind-00000001,70,Female,Bihar,Patna,Semi-Urban,Diarrhea,Waterborne,2018-01-01,2018,January,Winter,Never,A+,Employer,Medication,Government,21,102.0,Senior
1,Ind-00000002,27,Other,Gujarat,Surat,Urban,Chikungunya,Vector-Borne,2018-01-01,2018,January,Winter,Never,O+,Uninsured,Medication,Government,0,1151.0,Adult
2,Ind-00000003,66,Other,Jharkhand,Bokaro,Rural,Hypertension,Non-Communicable,2018-01-01,2018,January,Winter,Never,B+,Private,Medication,Government,2,89.0,Senior
3,Ind-00000004,27,Female,Karnataka,Hubli,Rural,Tuberculosis,Infectious,2018-01-01,2018,January,Winter,Never,O-,Private,Surgery,Government,9,1269.0,Adult
4,Ind-00000005,40,Male,Karnataka,Belagavi,Rural,Chronic Kidney Disease,Non-Communicable,2018-01-01,2018,January,Winter,Former,A+,Ayushman Bharat,Palliative,Private,31,670576.0,Adult

In [156]:
df.to_csv('disease_trend.csv')